import random
from datetime import datetime, timedelta
from geopy.geocoders import Nominatim
from timezonefinder import TimezoneFinder
from zoneinfo import ZoneInfo
from babel import Locale
from babel.dates import format_datetime

from tgbot.middlewares.i18n.i18n_format import localization_format_new as lf


async def get_timezone(city_name: str, language: str, time_format: int, utc: str = None) -> tuple:
    """Возвращает временную зону и текущее время для города."""
    pass

async def get_timezone_new(tz: str, language: str, time_format: int) -> tuple:
    """Упрощенная версия получения времени по временной зоне."""
    pass

def get_localized_date(reminder_time: datetime, user_locale: str,
                      user_timezone: str, format_time: int) -> str:
    """Форматирует дату напоминания с учетом локали."""
    pass

def format_reminder_time(reminder_time: datetime,
                        user_language: str,
                        format_time: int) -> str:
    """Базовое форматирование времени напоминания."""
    pass

async def get_ex_reminders(lang, format_time):
    reminders_ru = [
        "Встреча с клиентом в пятницу в 14",
        "Позвонить другу в 20",
        "Записаться к врачу на 10:30 в понедельник",
        "Обсудить проект с коллегой завтра в 15",
        "Выйти на прогулку через 30 минут",
        "Собеседование в четверг в 11",
        "Проверить почту через 15 минут",
        "Записаться в автошколу на послезавтра в 10",
        "Сдать отчёт начальнику в пятницу в 17:30",
        "Написать другу в 18:45",
        "Постирать вещи через 1 час",
        "Оплатить коммунальные услуги завтра утром",
        "Разобрать документы после работы в 19",
        "Купить продукты в 19",
        "Полить цветы через 3 дня",
        "Проверить холодильник перед походом в магазин через 30 мин",
        "Заправить постель через 15 минут",
        "Приготовить обед завтра в 12",
        "Вынести мусор вечером",
        "Протереть пыль через 40 минут",
        "Тренировка в субботу в 10",
        "Выпить воды через 20 минут",
        "Принять витамины утром",
        "Йога перед сном в 22",
        "Сделать зарядку через 10 минут",
        "Записаться на массаж в пятницу",
        "Проверить вес завтра утром",
        "Ложиться спать в 23:30",
        "Сходить на пробежку в воскресенье 7 утра",
        "Медитация через 1 час",
        "Встреча в среду в 17:30",
        "Убраться через 2 часа",
        "Тренировка завтра в 16",
        "Позвонить по работе завтра в 19",
        "Забрать посылку с почты через 2 часа",
        "Сделать перерыв каждые 4 часа",
        "Опубликовать пост в соцсетях в 20",
        "Проверить расписание через 15 мин",
        "Купить билеты в кино в субботу вечером",
        "Посмотреть вебинар завтра в 18",
        "Заполнить анкету через 45 минут",
        "Почитать книгу перед сном через 25 мин",
        "Уведомить коллегу о переносе встречи в 10 утра",
        "Оплатить счет через 5 мин",
        "Позаниматься английским через 30 минут",
        "Забрать ребёнка из школы в 15",
        "Написать список покупок завтра утром",
        "Отправить отчёт в 12",
        "Помыть машину в субботу днем",
        "Посетить стоматолога через неделю в 12",
        "Убрать рабочий стол через 20 минут",
        "Приготовить завтрак завтра в 8",
        "Прогуляться в парке вечером",
        "Заказать еду в 19:30",
        "Посетить тренажёрный зал в среду в 17",
        "Закончить проект в 18:30",
        "Записаться к парикмахеру в четверг утром",
        "Проверить батарею ноутбука перед встречей через 2 часа",
        "Приготовить ужин в 18",
        "Позвонить в банк через 3 часа",
        "Записаться на вебинар на понедельник в 12",
        "Подготовить документы в 17:00",
        "Сделать уборку в комнате в воскресенье утром",
        "Зарядить телефон через 20 мин",
        "Проверить расписание поездов вечером",
        "Разобрать старые вещи в шкафу через 3 часа",
        "Отправить письмо в 16",
        "Настроить Wi-Fi роутер через 30 минут",
        "Сделать заказ на сайте через 25 минут",
        "Написать резюме вечером",
        "Оплатить интернет вечером",
        "Выбрать подарок на день рождения послезавтра в 10 утра",
        "Сделать перерыв на кофе через 10 минут",
        "Записаться на йогу в четверг утром",
        "Приготовить смузи завтра утром",
        "Важная встреча через час",
        "Заказать лекарства через 5 дней",
        "Записать идеи для нового проекта завтра днем",
        "Спланировать поездку на выходные через 1 час",
        "Сделать заказ еды через 1 час",
        "Оплатить налоги через 20 дней",
        "Отправить файл заказчику в 14:00",
        "Выключить компьютер через 30 мин",
        "Проверить уровень масла в машине через неделю",
        "Подготовить список дел на неделю завтра вечером",
        "Закончить чтение книги через 30 минут",
        "Сделать фото для документа через 2 недели",
        "Разгрузить телефон от ненужных файлов вечером",
        "Купить кофе в магазине через 5 мин",
        "Почистить обувь через час",
        "Забронировать столик в ресторане в пятницу утром",
        "Сменить постельное бельё в субботу утром",
        "Подготовиться к экзамену через 1 час",
        "Отметить важные даты через 3 часа",
        "Записаться на курсы программирования 15 марта в 14:30",
        "Подготовить документы к поездке 3 июля в 10:00",
        "Купить подарки к Новому году 20 декабря в 18:00",
        "Оплатить страховку на автомобиль 5 сентября 2025 в 12:00",
        "Спланировать отпуск на лето 1 мая в 16:45",
        "Подать налоговую декларацию 30 апреля в 15:00",
        "Записаться к врачу 22 ноября в 09:30",
        "Обновить программное обеспечение на ноутбуке 10 июня в 19:15",
        "Купить билеты на концерт 8 августа в 17:20",
        "Забронировать отель на отдых 2 февраля 2025 в 13:00",
        "Оформить подписку на сервис 1 октября в 11:10",
        "Перенести встречу с клиентом на 27 марта в 14:00",
        "Выступить с докладом на конференции 18 июня в 09:00",
        "Записать ребёнка в секцию 5 апреля в 15:30",
        "Поздравить друга с днём рождения 12 сентября в 08:00",
        "Проверить отчёт перед сдачей 29 мая в 16:00",
        "Посетить выставку современного искусства 21 ноября 2025 в 13:45",
        "Сдать экзамен 10 декабря в 10:00",
        "Поменять шины на зимние 1 ноября в 18:30",
        "Запланировать новогодний ужин 24 декабря 2025 в 20:00"
    ]

    reminders_en_24 = [
        "Meeting with client on Friday at 14:00",
        "Call a friend at 20:00",
        "Make a doctor's appointment for 10:30 on Monday",
        "Discuss project with colleague tomorrow at 15:00",
        "Go for a walk in 30 minutes",
        "Job interview on Thursday at 11:00",
        "Check email in 15 minutes",
        "Make an appointment for driving school in 2 days",
        "Submit report to boss on Friday at 17:30",
        "Write to a friend at 18:45",
        "Do laundry in 1 hour",
        "Pay utility bills tomorrow morning",
        "Sort documents after work at 19:00",
        "Buy groceries at 19:00",
        "Water flowers in 3 days",
        "Check fridge before going to store in 30 minutes",
        "Make the bed in 15 minutes",
        "Prepare lunch tomorrow at 12:00",
        "Take out the trash in the evening",
        "Dust in 40 minutes",
        "Workout on Saturday at 10:00",
        "Drink water in 20 minutes",
        "Take vitamins in the morning",
        "Do yoga before sleep at 22:00",
        "Do morning exercise in 10 minutes",
        "Make an appointment for massage on Friday",
        "Check weight tomorrow morning",
        "Go to bed at 23:30",
        "Go for a run on Sunday at 7:00 AM",
        "Meditate in 1 hour",
        "Meeting on Wednesday at 17:30",
        "Clean up in 2 hours",
        "Workout tomorrow at 16:00",
        "Call for work tomorrow at 19:00",
        "Pick up parcel from post office in 2 hours",
        "Take a break every 4 hours",
        "Post on social media at 20:00",
        "Check schedule in 15 minutes",
        "Buy movie tickets on Saturday evening",
        "Watch webinar tomorrow at 18:00",
        "Fill out form in 45 minutes",
        "Read a book before sleep in 25 minutes",
        "Notify colleague about rescheduled meeting at 10 AM",
        "Pay bill in 5 minutes",
        "Practice English in 30 minutes",
        "Pick up child from school at 15:00",
        "Make shopping list tomorrow morning",
        "Send report at 12:00",
        "Wash car on Saturday afternoon",
        "Visit dentist in a week at 12:00",
        "Tidy up desk in 20 minutes",
        "Make breakfast tomorrow at 8:00",
        "Go for a walk in the park in the evening",
        "Order food at 19:30",
        "Visit gym on Wednesday at 17:00",
        "Finish project at 18:30",
        "Book a haircut appointment on Thursday morning",
        "Check laptop battery before meeting in 2 hours",
        "Make dinner at 18:00",
        "Call bank in 3 hours",
        "Sign up for a webinar on Monday at 12:00",
        "Prepare documents at 17:00",
        "Clean room on Sunday morning",
        "Charge phone in 20 minutes",
        "Check train schedule in the evening",
        "Sort old things in the closet in 3 hours",
        "Send email at 16:00",
        "Set up Wi-Fi router in 30 minutes",
        "Place an order on the website in 25 minutes",
        "Write a resume in the evening",
        "Pay for internet in the evening",
        "Choose birthday gift in 2 days at 10 AM",
        "Take a coffee break in 10 minutes",
        "Sign up for yoga on Thursday morning",
        "Make smoothie tomorrow morning",
        "Important meeting in 1 hour",
        "Order medicine in 5 days",
        "Write down ideas for a new project tomorrow afternoon",
        "Plan weekend trip in 1 hour",
        "Order food in 1 hour",
        "Pay taxes in 20 days",
        "Send file to client at 14:00",
        "Turn off computer in 30 minutes",
        "Check oil level in car in a week",
        "Prepare to-do list for the week tomorrow evening",
        "Finish reading book in 30 minutes",
        "Take photo for document in 2 weeks",
        "Clear unnecessary files from phone in the evening",
        "Buy coffee at the store in 5 minutes",
        "Clean shoes in 1 hour",
        "Book a table at restaurant on Friday morning",
        "Change bed linens on Saturday morning",
        "Prepare for exam in 1 hour",
        "Mark important dates in 3 hours",
        "Sign up for programming courses on March 15 at 14:30",
        "Prepare documents for the trip on July 3 at 10:00",
        "Buy gifts for the New Year on December 20 at 18:00",
        "Pay car insurance on September 5, 2025, at 12:00",
        "Plan a summer vacation on May 1 at 16:45",
        "Submit a tax return on April 30 at 15:00",
        "Make a doctor's appointment on November 22 at 09:30",
        "Update software on the laptop on June 10 at 19:15",
        "Buy concert tickets on August 8 at 17:20",
        "Book a hotel for vacation on February 2, 2025, at 13:00",
        "Subscribe to a service on October 1 at 11:10",
        "Reschedule a meeting with a client to March 27 at 14:00",
        "Give a talk at a conference on June 18 at 09:00",
        "Enroll a child in a sports club on April 5 at 15:30",
        "Congratulate a friend on their birthday on September 12 at 08:00",
        "Review the report before submission on May 29 at 16:00",
        "Visit a contemporary art exhibition on November 21, 2025, at 13:45",
        "Take an exam on December 10 at 10:00",
        "Change tires to winter ones on November 1 at 18:30",
        "Plan the New Year's dinner on December 24, 2025, at 20:00"
    ]

    reminders_en_12 = [
        "Meeting with client on Friday at 2:00 p.m.",
        "Call a friend at 8:00 p.m.",
        "Make a doctor's appointment for 10:30 a.m. on Monday",
        "Discuss project with colleague tomorrow at 3:00 p.m.",
        "Go for a walk in 30 minutes",
        "Job interview on Thursday at 11:00 a.m.",
        "Check email in 15 minutes",
        "Make an appointment for driving school in 2 days",
        "Submit report to boss on Friday at 5:30 p.m.",
        "Write to a friend at 6:45 p.m.",
        "Do laundry in 1 hour",
        "Pay utility bills tomorrow morning",
        "Sort documents after work at 7:00 p.m.",
        "Buy groceries at 7:00 p.m.",
        "Water flowers in 3 days",
        "Check fridge before going to store in 30 minutes",
        "Make the bed in 15 minutes",
        "Prepare lunch tomorrow at 12:00 p.m.",
        "Take out the trash in the evening",
        "Dust in 40 minutes",
        "Workout on Saturday at 10:00 a.m.",
        "Drink water in 20 minutes",
        "Take vitamins in the morning",
        "Do yoga before sleep at 10:00 p.m.",
        "Do morning exercise in 10 minutes",
        "Make an appointment for massage on Friday",
        "Check weight tomorrow morning",
        "Go to bed at 11:30 p.m.",
        "Go for a run on Sunday at 7:00 a.m.",
        "Meditate in 1 hour",
        "Meeting on Wednesday at 5:30 p.m.",
        "Clean up in 2 hours",
        "Workout tomorrow at 4:00 p.m.",
        "Call for work tomorrow at 7:00 p.m.",
        "Pick up parcel from post office in 2 hours",
        "Take a break every 4 hours",
        "Post on social media at 8:00 p.m.",
        "Check schedule in 15 minutes",
        "Buy movie tickets on Saturday evening",
        "Watch webinar tomorrow at 6:00 p.m.",
        "Fill out form in 45 minutes",
        "Read a book before sleep in 25 minutes",
        "Notify colleague about rescheduled meeting at 10:00 a.m.",
        "Pay bill in 5 minutes",
        "Practice English in 30 minutes",
        "Pick up child from school at 3:00 p.m.",
        "Make shopping list tomorrow morning",
        "Send report at 12:00 p.m.",
        "Wash car on Saturday afternoon",
        "Visit dentist in a week",
        "Tidy up desk in 20 minutes",
        "Make breakfast tomorrow at 8:00 a.m.",
        "Go for a walk in the park in the evening",
        "Order food at 7:30 p.m.",
        "Visit gym on Wednesday at 5:00 p.m.",
        "Finish project at 6:30 p.m.",
        "Book a haircut appointment on Thursday morning",
        "Check laptop battery before meeting in 2 hours",
        "Make dinner at 6:00 p.m.",
        "Call bank in 3 hours",
        "Sign up for a webinar on Monday at 12:00 p.m.",
        "Prepare documents at 5:00 p.m.",
        "Clean room on Sunday morning",
        "Charge phone in 20 minutes",
        "Check train schedule in the evening",
        "Sort old things in the closet in 3 hours",
        "Send email at 4:00 p.m.",
        "Set up Wi-Fi router in 30 minutes",
        "Place an order on the website in 25 minutes",
        "Write a resume in the evening",
        "Pay for internet in the evening",
        "Choose birthday gift in 2 days at 10:00 a.m.",
        "Take a coffee break in 10 minutes",
        "Sign up for yoga on Thursday morning",
        "Make smoothie tomorrow morning",
        "Important meeting in 1 hour",
        "Order medicine in 5 days",
        "Write down ideas for a new project tomorrow afternoon",
        "Plan weekend trip in 1 hour",
        "Order food in 1 hour",
        "Pay taxes in 20 days",
        "Send file to client at 2:00 p.m.",
        "Turn off computer in 30 minutes",
        "Check oil level in car in a week",
        "Prepare to-do list for the week tomorrow evening",
        "Finish reading book in 30 minutes",
        "Take photo for document in 2 weeks",
        "Clear unnecessary files from phone in the evening",
        "Buy coffee at the store in 5 minutes",
        "Clean shoes in 1 hour",
        "Book a table at restaurant on Friday morning",
        "Change bed linens on Saturday morning",
        "Prepare for exam in 1 hour",
        "Mark important dates in 3 hours",
        "Sign up for programming courses on March 15 at 2:30 pm",
        "Prepare documents for the trip on July 3 at 10:00 am",
        "Buy gifts for the New Year on December 20 at 6:00 pm",
        "Pay car insurance on September 5, 2025, at 12:00 pm",
        "Plan a summer vacation on May 1 at 4:45 pm",
        "Submit a tax return on April 30 at 3:00 pm",
        "Make a doctor's appointment on November 22 at 9:30 am",
        "Update software on the laptop on June 10 at 7:15 pm",
        "Buy concert tickets on August 8 at 5:20 pm",
        "Book a hotel for vacation on February 2, 2025, at 1:00 pm",
        "Subscribe to a service on October 1 at 11:10 am",
        "Reschedule a meeting with a client to March 27 at 2:00 pm",
        "Give a talk at a conference on June 18 at 9:00 am",
        "Enroll a child in a sports club on April 5 at 3:30 pm",
        "Congratulate a friend on their birthday on September 12 at 8:00 am",
        "Review the report before submission on May 29 at 4:00 pm",
        "Visit a contemporary art exhibition on November 21, 2025, at 1:45 pm",
        "Take an exam on December 10 at 10:00 am",
        "Change tires to winter ones on November 1 at 6:30 pm",
        "Plan the New Year's dinner on December 24, 2025, at 8:00 pm"
    ]
    if lang == 'ru':
        return random.sample(reminders_ru, 2)
    elif lang == 'en' and format_time == 24:
        return random.sample(reminders_en_24, 2)
    else:
        return random.sample(reminders_en_12, 2)
